package com.stellarintel.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Structured Generative AI Diagnostic Response.
 *
 * <p>Phase 3 Contract:
 * Encapsulates the technical interpretation, potential contributing factors,
 * impacted subsystems, and recommended engineering investigations generated by
 * the Spring AI ChatModel.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GenAiDiagnosticResponse {

    /**
     * High-level executive technical diagnosis synthesized by the LLM.
     */
    private String diagnosticSummary;

    /**
     * Factual conditions observed from the deterministic telemetry baseline.
     */
    private List<String> observedConditions;

    /**
     * Plausible physical or operational mechanisms that could explain the symptoms.
     */
    private List<String> possibleContributingFactors;

    /**
     * Spacecraft functional subsystems implicated in the event (e.g., ADCS, Thermal, EPS).
     */
    private List<String> affectedSubsystems;

    /**
     * Step-by-step diagnostic verification and monitoring procedures recommended for ground operators.
     */
    private List<String> recommendedInvestigation;

    /**
     * Explicit operational limitations (e.g. simulation scope, missing historic telemetry).
     */
    private List<String> limitations;

    /**
     * Retrieved technical knowledge base sources utilized by the RAG pipeline.
     */
    private List<KnowledgeSourceDto> knowledgeSources;

    /**
     * Execution status of the GenAI layer (e.g. "SUCCESS", "OFFLINE_FALLBACK", "UNAVAILABLE").
     */
    private String status;

    /**
     * Safety and compliance disclaimer.
     */
    private String disclaimer;

    /**
     * Generation timestamp.
     */
    private String generatedAt;

    public GenAiDiagnosticResponse() {
        this.observedConditions = new ArrayList<>();
        this.possibleContributingFactors = new ArrayList<>();
        this.affectedSubsystems = new ArrayList<>();
        this.recommendedInvestigation = new ArrayList<>();
        this.limitations = new ArrayList<>();
        this.knowledgeSources = new ArrayList<>();
    }

    public GenAiDiagnosticResponse(String diagnosticSummary, List<String> observedConditions,
                                  List<String> possibleContributingFactors, List<String> affectedSubsystems,
                                  List<String> recommendedInvestigation, List<String> limitations,
                                  List<KnowledgeSourceDto> knowledgeSources,
                                  String status, String disclaimer, String generatedAt) {
        this.diagnosticSummary = diagnosticSummary;
        this.observedConditions = observedConditions != null ? observedConditions : new ArrayList<>();
        this.possibleContributingFactors = possibleContributingFactors != null ? possibleContributingFactors : new ArrayList<>();
        this.affectedSubsystems = affectedSubsystems != null ? affectedSubsystems : new ArrayList<>();
        this.recommendedInvestigation = recommendedInvestigation != null ? recommendedInvestigation : new ArrayList<>();
        this.limitations = limitations != null ? limitations : new ArrayList<>();
        this.knowledgeSources = knowledgeSources != null ? knowledgeSources : new ArrayList<>();
        this.status = status;
        this.disclaimer = disclaimer;
        this.generatedAt = generatedAt;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private String diagnosticSummary;
        private List<String> observedConditions = new ArrayList<>();
        private List<String> possibleContributingFactors = new ArrayList<>();
        private List<String> affectedSubsystems = new ArrayList<>();
        private List<String> recommendedInvestigation = new ArrayList<>();
        private List<String> limitations = new ArrayList<>();
        private List<KnowledgeSourceDto> knowledgeSources = new ArrayList<>();
        private String status = "SUCCESS";
        private String disclaimer = "AI-generated diagnostic interpretation for academic simulation. Not a real spacecraft flight command.";
        private String generatedAt = Instant.now().toString();

        public Builder diagnosticSummary(String diagnosticSummary) {
            this.diagnosticSummary = diagnosticSummary;
            return this;
        }

        public Builder observedConditions(List<String> observedConditions) {
            this.observedConditions = observedConditions != null ? observedConditions : new ArrayList<>();
            return this;
        }

        public Builder possibleContributingFactors(List<String> possibleContributingFactors) {
            this.possibleContributingFactors = possibleContributingFactors != null ? possibleContributingFactors : new ArrayList<>();
            return this;
        }

        public Builder affectedSubsystems(List<String> affectedSubsystems) {
            this.affectedSubsystems = affectedSubsystems != null ? affectedSubsystems : new ArrayList<>();
            return this;
        }

        public Builder recommendedInvestigation(List<String> recommendedInvestigation) {
            this.recommendedInvestigation = recommendedInvestigation != null ? recommendedInvestigation : new ArrayList<>();
            return this;
        }

        public Builder limitations(List<String> limitations) {
            this.limitations = limitations != null ? limitations : new ArrayList<>();
            return this;
        }

        public Builder knowledgeSources(List<KnowledgeSourceDto> knowledgeSources) {
            this.knowledgeSources = knowledgeSources != null ? knowledgeSources : new ArrayList<>();
            return this;
        }

        public Builder status(String status) {
            this.status = status;
            return this;
        }

        public Builder disclaimer(String disclaimer) {
            this.disclaimer = disclaimer;
            return this;
        }

        public Builder generatedAt(String generatedAt) {
            this.generatedAt = generatedAt;
            return this;
        }

        public GenAiDiagnosticResponse build() {
            return new GenAiDiagnosticResponse(
                    diagnosticSummary,
                    observedConditions,
                    possibleContributingFactors,
                    affectedSubsystems,
                    recommendedInvestigation,
                    limitations,
                    knowledgeSources,
                    status,
                    disclaimer,
                    generatedAt
            );
        }
    }

    /**
     * Creates a controlled fallback response when external LLM service is unavailable or unconfigured.
     */
    public static GenAiDiagnosticResponse fallback(String reason, String summaryText) {
        List<String> obs = new ArrayList<>();
        obs.add(summaryText != null ? summaryText : "Deterministic telemetry analysis completed.");

        List<String> factors = new ArrayList<>();
        factors.add("External GenAI model invocation deferred (" + reason + ").");

        List<String> subsystems = new ArrayList<>();
        subsystems.add("Telemetry Analysis Engine (Deterministic)");

        List<String> recs = new ArrayList<>();
        recs.add("Verify deterministic anomaly metrics in Mission Control dashboard.");
        recs.add("To enable live LLM reasoning, configure the OPENAI_API_KEY environment variable.");

        List<String> limits = new ArrayList<>();
        limits.add("LLM diagnostic reasoning layer is offline; deterministic numerical rules remain authoritative.");

        return GenAiDiagnosticResponse.builder()
                .diagnosticSummary("Deterministic telemetry analysis completed successfully. Generative AI diagnostic is currently in offline/standby mode: " + reason)
                .observedConditions(obs)
                .possibleContributingFactors(factors)
                .affectedSubsystems(subsystems)
                .recommendedInvestigation(recs)
                .limitations(limits)
                .status("OFFLINE_FALLBACK")
                .disclaimer("Simulated academic telemetry. Deterministic analysis was executed by pure Java rules.")
                .generatedAt(Instant.now().toString())
                .build();
    }

    // Explicit getters and setters to ensure reliability across all JDK versions
    public String getDiagnosticSummary() {
        return diagnosticSummary;
    }

    public void setDiagnosticSummary(String diagnosticSummary) {
        this.diagnosticSummary = diagnosticSummary;
    }

    public List<String> getObservedConditions() {
        return observedConditions;
    }

    public void setObservedConditions(List<String> observedConditions) {
        this.observedConditions = observedConditions;
    }

    public List<String> getPossibleContributingFactors() {
        return possibleContributingFactors;
    }

    public void setPossibleContributingFactors(List<String> possibleContributingFactors) {
        this.possibleContributingFactors = possibleContributingFactors;
    }

    public List<String> getAffectedSubsystems() {
        return affectedSubsystems;
    }

    public void setAffectedSubsystems(List<String> affectedSubsystems) {
        this.affectedSubsystems = affectedSubsystems;
    }

    public List<String> getRecommendedInvestigation() {
        return recommendedInvestigation;
    }

    public void setRecommendedInvestigation(List<String> recommendedInvestigation) {
        this.recommendedInvestigation = recommendedInvestigation;
    }

    public List<String> getLimitations() {
        return limitations;
    }

    public void setLimitations(List<String> limitations) {
        this.limitations = limitations;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getDisclaimer() {
        return disclaimer;
    }

    public void setDisclaimer(String disclaimer) {
        this.disclaimer = disclaimer;
    }

    public String getGeneratedAt() {
        return generatedAt;
    }

    public void setGeneratedAt(String generatedAt) {
        this.generatedAt = generatedAt;
    }

    public List<KnowledgeSourceDto> getKnowledgeSources() {
        return knowledgeSources;
    }

    public void setKnowledgeSources(List<KnowledgeSourceDto> knowledgeSources) {
        this.knowledgeSources = knowledgeSources;
    }
}
